name: 'Bill.com x Airtable Action'
description: 'Run a Javascript file that uses bill_com.js and airtable.js'
inputs:
  filename:
    description: 'The Javascript file name (without the extension)'
    required: true
    default: ${{ github.job }}
  primary-org:
    description: 'The primary Bill.com Org'
    required: true
    default: ${{ secrets.PRIMARY_ORG }}
  airtable-api-key:
    description: 'The Airtable API key to use for Airtable interactions'
    required: true
    default: ${{ secrets.AIRTABLE_API_KEY }}
  airtable-base-id:
    description: 'The ID of the Airtable Base used in the target file'
    required: true
    default: ${{ secrets.BILL_COM_INTEGRATION_BASE_ID }}
  bill-com-dev-key:
    description: 'The Bill.com developer key for API access'
    required: true
    default: ${{ secrets.BILL_COM_DEV_KEY }}
  bill-com-user-name:
    description: 'The Bill.com email for login'
    required: true
    default: ${{ secrets.BILL_COM_USER_NAME }}
  bill-com-passwork:
    description: 'The Bill.com password for login'
    required: true
    default: ${{ secrets.BILL_COM_PASSWORD }}
runs:
  using: 'node16'
  main: 'dist/${{ inputs.filename }}/index.js'
