name: Accounting Sync
on:
  workflow_dispatch:
jobs:
  accounting_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: RSMvmtTech/Bill.com-Airtable-Integration@main
        with:
          internal-customer-id: ${{ secrets.INTERNAL_CUSTOMER_ID }}
