name: Base Workflow
on:
  workflow_call:
    inputs:
      filename:
        description: 'The Javascript file name (without the extension)'
        required: true
        type: string
      use-accounting-base:
        description:
          'true: Accounting Terminology Index Base; false: Bill.com Integration Base'
        required: false
        default: false
        type: boolean
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - id: get-airtable-base-id
        run: |
          if [ $inputs.use-accounting-base = true ] ; then
            id=$secrets.ACCOUNTING_TERMINOLOGY_INDEX_BASE_ID
          else
            id=$secrets.BILL_COM_INTEGRATION_BASE_ID
          fi
          echo '::set-output name=id::$id'
      - uses: RSMvmtTech/Bill.com-Airtable-Integration@main
        with:
          filename: ${{ inputs.filename }}
          primary-org: ${{ secrets.PRIMARY_ORG }}
          airtable-api-key: ${{ secrets.AIRTABLE_API_KEY }}
          airtable-base-id: ${{ steps.airtable-base-id.id }}
          bill-com-dev-key: ${{ secrets.BILL_COM_DEV_KEY }}
          bill-com-user-name: ${{ secrets.BILL_COM_USER_NAME }}
          bill-com-password: ${{ secrets.BILL_COM_PASSWORD }}
          internal-customer-id: ${{ secrets.INTERNAL_CUSTOMER_ID }}
          ecr-approver-user-profile-id: ${{ secrets.ECR_APPROVER_USER_PROFILE_ID }}
          integromat-hook-prefix: ${{ secrets.INTEGROMAT_HOOK_PREFIX }}
