name: Build Distribution File
on:
  push:
    paths:
      - src/*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: |
          git add dist
          git commit -m "Build dirstribution file"
          git push
