name: Main Workflow
on:
  workflow_dispatch:
jobs:
  accounting_sync:
    runs-on: ubuntu-latest
    uses: ./.github/workflow/base.yml
    with:
      airtable-base-id: ${{ secrets.ACCOUNTING_TERMINOLOGY_INDEX_BASE_ID }}
      internal-customer-id: ${{ secrets.INTERNAL_CUSTOMER_ID }}
    secrets: inherit
