name: Main Workflow
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  accounting_sync:
    uses: ./.github/workflows/base.yml
    with:
      filename: 'accounting_sync'
      use-accounting-base: true
    secrets: inherit
